/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.22
 * Generated at: 2019-08-09 14:15:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("  <title>登录页</title>\n");
      out.write("\n");
      out.write("  <!-- CSS -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"http://fonts.googleapis.com/css?family=Roboto:400,100,300,500\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"assets/css/font-awesome.min.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"assets/css/form-elements.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"assets/css/styleforindex.css\">\n");
      out.write("\n");
      out.write("  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n");
      out.write("  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("  <!--[if lt IE 9]>\n");
      out.write("  <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\n");
      out.write("  <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\n");
      out.write("  <![endif]-->\n");
      out.write("\n");
      out.write("  <!-- Favicon and touch icons -->\n");
      out.write("  <link rel=\"shortcut icon\" href=\"assets/ico/favicon.png\">\n");
      out.write("  <link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=\"assets/ico/apple-touch-icon-144-precomposed.png\">\n");
      out.write("  <link rel=\"apple-touch-icon-precomposed\" sizes=\"114x114\" href=\"assets/ico/apple-touch-icon-114-precomposed.png\">\n");
      out.write("  <link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\" href=\"assets/ico/apple-touch-icon-72-precomposed.png\">\n");
      out.write("  <link rel=\"apple-touch-icon-precomposed\" href=\"assets/ico/apple-touch-icon-57-precomposed.png\">\n");
      out.write("\n");
      out.write("  <script>\n");
      out.write("    function x() {\n");
      out.write("      var form1 = document.getElementById('form1');\n");
      out.write("      var type = document.getElementById('type');\n");
      out.write("      if (type.value == '0'){\n");
      out.write("        form1.action = 'admin/login';\n");
      out.write("      } else if (type.value == '1'){\n");
      out.write("        form1.action = 'vip/login';\n");
      out.write("      } else {\n");
      out.write("        form1.action = 'agency/login';\n");
      out.write("      }\n");
      out.write("      form1.submit();\n");
      out.write("    }\n");
      out.write("  </script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<!-- Top content -->\n");
      out.write("<div class=\"top-content\">\n");
      out.write("\n");
      out.write("  <div class=\"inner-bg\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-sm-8 col-sm-offset-2 text\">\n");
      out.write("          <h1><strong>欢迎访问</strong> NJUST旅游平台</h1>\n");
      out.write("          <div class=\"description\">\n");
      out.write("            <p>\n");
      out.write("             您可以查询最新景点信息及旅社路线情况 <a href=\"#\"><strong>NJUST旅游平台</strong></a>将为您提供最新的消息!\n");
      out.write("            </p>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-sm-6 col-sm-offset-3 form-box\">\n");
      out.write("          <div class=\"form-top\">\n");
      out.write("            <div class=\"form-top-left\">\n");
      out.write("              <h3>网站登录</h3>\n");
      out.write("              <p>输入用户名及密码进行登录:</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-top-right\">\n");
      out.write("              <i class=\"fa fa-key\"></i>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"form-bottom\">\n");
      out.write("            <form role=\"form\" id=\"form1\" name=\"form1\" method=\"post\" class=\"login-form\">\n");
      out.write("              <div class=\"form-group\">\n");
      out.write("                <label class=\"sr-only\" for=\"username\">用户名</label>\n");
      out.write("                <input type=\"text\" name=\"username\" placeholder=\"用户名...\" class=\"username form-control\" id=\"username\">\n");
      out.write("              </div>\n");
      out.write("              <div class=\"form-group\">\n");
      out.write("                <label class=\"sr-only\" for=\"password\">密码</label>\n");
      out.write("                <input type=\"password\" name=\"password\" placeholder=\"密码...\" class=\"password form-control\" id=\"password\">\n");
      out.write("              </div>\n");
      out.write("              <div class=\"form-group\">\n");
      out.write("                <label class=\"sr-only\" for=\"type\">用户类型</label>\n");
      out.write("                <select id=\"type\" name=\"type\" class=\"type form-control\">\n");
      out.write("                  <option value=\"0\">管理员</option>\n");
      out.write("                  <option value=\"1\">会员</option>\n");
      out.write("                  <option value=\"2\">旅行社</option>\n");
      out.write("                </select>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"form-group\">\n");
      out.write("                <button id=\"bu1\" name=\"bu1\" type=\"button\" class=\"btn\" onclick=\"x()\">确认登录</button>\n");
      out.write("              </div>\n");
      out.write("            </form>\n");
      out.write("            <div class=\"form_reg_btn\">\n");
      out.write("              <span>没有帐号？</span>\n");
      out.write("              <a href=\"register.jsp\" style=\"margin-right:265px;\">马上注册</a>\n");
      out.write("              <a href=\"\">忘记密码?</a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form_reg_btn\">\n");
      out.write("              <span>不想注册？</span>\n");
      out.write("              <a href=\"main.jsp\" style=\"margin-right:265px;\">游客入口</a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form_forget_btn\">\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Javascript -->\n");
      out.write("<script src=\"assets/js/jquery-1.11.1.min.js\"></script>\n");
      out.write("<script src=\"assets/js/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"assets/js/jquery.backstretch.min.js\"></script>\n");
      out.write("<script src=\"assets/js/scripts.js\"></script>\n");
      out.write("\n");
      out.write("<!--[if lt IE 10]>\n");
      out.write("<script src=\"assets/js/placeholder.js\"></script>\n");
      out.write("<![endif]-->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
