/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.22
 * Generated at: 2019-09-04 11:12:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
 String path = request.getContextPath();
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>管理员界面</title>\r\n");
      out.write("\r\n");
      out.write("    <link href=\"");
      out.print(path);
      out.write("/assets/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(path);
      out.write("/assets/css/datepicker3.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(path);
      out.write("/assets/css/adminmain.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"");
      out.print(path);
      out.write("/assets/js/html5shiv.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(path);
      out.write("/assets/js/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#sidebar-collapse\">\r\n");
      out.write("                <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"#\">资源管理</a>\r\n");
      out.write("            <ul class=\"user-menu\">\r\n");
      out.write("                <li class=\"dropdown pull-right\">\r\n");
      out.write("                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><span class=\"glyphicon glyphicon-user\"></span>用户<span class=\"caret\"></span></a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("                        <li><a href=\"/travel/getPersonal\"><span class=\"glyphicon glyphicon-user\"></span> 个人信息</a></li>\r\n");
      out.write("                        <li><a href=\"/travel/index.jsp\"><span class=\"glyphicon glyphicon-log-out\"></span> 登出</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div><!-- /.container-fluid -->\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div id=\"sidebar-collapse\" class=\"col-sm-3 col-lg-2 sidebar\">\r\n");
      out.write("\r\n");
      out.write("    <ul class=\"nav menu\">\r\n");
      out.write("        <li><a style=font-size:30px;>功能模块</a></li>\r\n");
      out.write("        <!--\r\n");
      out.write("            <li class=\"parent \">\r\n");
      out.write("            <a href=\"#\">\r\n");
      out.write("                <span class=\"glyphicon glyphicon-list\"></span> 景点信息管理<span data-toggle=\"collapse\" href=\"#sub-item-1\" class=\"icon pull-right\"><em class=\"glyphicon glyphicon-s glyphicon-plus\"></em></span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"children collapse \" id=\"sub-item-1\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a class=\"\" href=\"#\">\r\n");
      out.write("                        <span class=\"glyphicon glyphicon-share-alt\"></span> 推荐景点更改\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a class=\"\" href=\"#\">\r\n");
      out.write("                        <span class=\"glyphicon glyphicon-share-alt\"></span> 景点信息认证\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li role=\"presentation\" class=\"divider\"></li>\r\n");
      out.write("        <li class=\"parent \">\r\n");
      out.write("            <a href=\"#\">\r\n");
      out.write("                <span class=\"glyphicon glyphicon-list\"></span> 用户信息管理<span data-toggle=\"collapse\" href=\"#sub-item-2\" class=\"icon pull-right\"><em class=\"glyphicon glyphicon-s glyphicon-plus\"></em></span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"children collapse\" id=\"sub-item-2\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a class=\"\" href=\"#\">\r\n");
      out.write("                        <span class=\"glyphicon glyphicon-share-alt\"></span> 查看用户信息\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a class=\"\" href=\"#\">\r\n");
      out.write("                        <span class=\"glyphicon glyphicon-share-alt\"></span> 查看交易记录\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li role=\"presentation\" class=\"divider\"></li>\r\n");
      out.write("        -->\r\n");
      out.write("        <li class=\"parent \">\r\n");
      out.write("            <a href=\"#\">\r\n");
      out.write("                <span class=\"glyphicon glyphicon-list\"></span> 注册认证管理<span data-toggle=\"collapse\" href=\"#sub-item-3\" class=\"icon pull-right\"><em class=\"glyphicon glyphicon-s glyphicon-plus\"></em></span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"children collapse\" id=\"sub-item-3\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a class=\"\" href=\"#\" onclick=\"showAtRight('/travel/admin/getVip')\">\r\n");
      out.write("                        <span class=\"glyphicon glyphicon-share-alt\"></span> 会员认证\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a class=\"\" href=\"#\" onclick=\"showAtRight('/travel/admin/getAgency')\">\r\n");
      out.write("                        <span class=\"glyphicon glyphicon-share-alt\"></span> 旅行社认证\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li role=\"presentation\" class=\"divider\"></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</div><!--/.sidebar-->\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row\" id=\"content\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!--\r\n");
      out.write("        <div class=\"row\" id=\"content\">\r\n");
      out.write("        <div class=\"col-xs-12 col-md-6 col-lg-3\">\r\n");
      out.write("            <div class=\"panel panel-blue panel-widget \">\r\n");
      out.write("                <div class=\"row no-padding\">\r\n");
      out.write("                    <div class=\"col-sm-3 col-lg-5 widget-left\">\r\n");
      out.write("                        <em class=\"glyphicon glyphicon-shopping-cart glyphicon-l\"></em>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-sm-9 col-lg-7 widget-right\">\r\n");
      out.write("                        <div class=\"large\">这里</div>\r\n");
      out.write("                        <div class=\"text-muted\">zheli</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-12 col-md-6 col-lg-3\">\r\n");
      out.write("            <div class=\"panel panel-orange panel-widget\">\r\n");
      out.write("                <div class=\"row no-padding\">\r\n");
      out.write("                    <div class=\"col-sm-3 col-lg-5 widget-left\">\r\n");
      out.write("                        <em class=\"glyphicon glyphicon-comment glyphicon-l\"></em>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-sm-9 col-lg-7 widget-right\">\r\n");
      out.write("                        <div class=\"large\">现在</div>\r\n");
      out.write("                        <div class=\"text-muted\">now</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-12 col-md-6 col-lg-3\">\r\n");
      out.write("            <div class=\"panel panel-teal panel-widget\">\r\n");
      out.write("                <div class=\"row no-padding\">\r\n");
      out.write("                    <div class=\"col-sm-3 col-lg-5 widget-left\">\r\n");
      out.write("                        <em class=\"glyphicon glyphicon-user glyphicon-l\"></em>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-sm-9 col-lg-7 widget-right\">\r\n");
      out.write("                        <div class=\"large\">什么</div>\r\n");
      out.write("                        <div class=\"text-muted\">what</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-12 col-md-6 col-lg-3\">\r\n");
      out.write("            <div class=\"panel panel-red panel-widget\">\r\n");
      out.write("                <div class=\"row no-padding\">\r\n");
      out.write("                    <div class=\"col-sm-3 col-lg-5 widget-left\">\r\n");
      out.write("                        <em class=\"glyphicon glyphicon-stats glyphicon-l\"></em>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-sm-9 col-lg-7 widget-right\">\r\n");
      out.write("                        <div class=\"large\">都没有</div>\r\n");
      out.write("                        <div class=\"text-muted\">nothing</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    -->\r\n");
      out.write("\r\n");
      out.write("</div>\t<!--/.main-->\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/assets/js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/assets/js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    $('#calendar').datepicker({\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    !function ($) {\r\n");
      out.write("        $(document).on(\"click\",\"ul.nav li.parent > a > span.icon\", function(){\r\n");
      out.write("            $(this).find('em:first').toggleClass(\"glyphicon-minus\");\r\n");
      out.write("        });\r\n");
      out.write("        $(\".sidebar span.icon\").find('em:first').addClass(\"glyphicon-plus\");\r\n");
      out.write("    }(window.jQuery);\r\n");
      out.write("\r\n");
      out.write("    $(window).on('resize', function () {\r\n");
      out.write("        if ($(window).width() > 768) $('#sidebar-collapse').collapse('show')\r\n");
      out.write("    })\r\n");
      out.write("    $(window).on('resize', function () {\r\n");
      out.write("        if ($(window).width() <= 767) $('#sidebar-collapse').collapse('hide')\r\n");
      out.write("    })\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("    /*\r\n");
      out.write("     * 对选中的标签激活active状态，对先前处于active状态但之后未被选中的标签取消active\r\n");
      out.write("     * （实现左侧菜单中的标签点击后变色的效果）\r\n");
      out.write("     */\r\n");
      out.write("    $(document).ready(function () {\r\n");
      out.write("        $('ul.nav > li').click(function (e) {\r\n");
      out.write("            //e.preventDefault();    加上这句则导航的<a>标签会失效\r\n");
      out.write("            $('ul.nav > li').removeClass('active');\r\n");
      out.write("            $(this).addClass('active');\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    /*\r\n");
      out.write("     * 解决ajax返回的页面中含有javascript的办法：\r\n");
      out.write("     * 把xmlHttp.responseText中的脚本都抽取出来，不管AJAX加载的HTML包含多少个脚本块，我们对找出来的脚本块都调用eval方法执行它即可\r\n");
      out.write("     */\r\n");
      out.write("    function executeScript(html)\r\n");
      out.write("    {\r\n");
      out.write("\r\n");
      out.write("        var reg = /<script[^>]*>([^\\x00]+)$/i;\r\n");
      out.write("        //对整段HTML片段按<\\/script>拆分\r\n");
      out.write("        var htmlBlock = html.split(\"<\\/script>\");\r\n");
      out.write("        for (var i in htmlBlock)\r\n");
      out.write("        {\r\n");
      out.write("            var blocks;//匹配正则表达式的内容数组，blocks[1]就是真正的一段脚本内容，因为前面reg定义我们用了括号进行了捕获分组\r\n");
      out.write("            if (blocks = htmlBlock[i].match(reg))\r\n");
      out.write("            {\r\n");
      out.write("                //清除可能存在的注释标记，对于注释结尾-->可以忽略处理，eval一样能正常工作\r\n");
      out.write("                var code = blocks[1].replace(/<!--/, '');\r\n");
      out.write("                try\r\n");
      out.write("                {\r\n");
      out.write("                    eval(code) //执行脚本\r\n");
      out.write("                }\r\n");
      out.write("                catch (e)\r\n");
      out.write("                {\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /*\r\n");
      out.write("     * 利用div实现左边点击右边显示的效果（以id=\"content\"的div进行内容展示）\r\n");
      out.write("     * 注意：\r\n");
      out.write("     *   ①：js获取网页的地址，是根据当前网页来相对获取的，不会识别根目录；\r\n");
      out.write("     *   ②：如果右边加载的内容显示页里面有css，必须放在主页（即例中的index.jsp）才起作用\r\n");
      out.write("     *   （如果单纯的两个页面之间include，子页面的css和js在子页面是可以执行的。 主页面也可以调用子页面的js。但这时要考虑页面中js和渲染的先后顺序 ）\r\n");
      out.write("    */\r\n");
      out.write("    function showAtRight(url) {\r\n");
      out.write("        var xmlHttp;\r\n");
      out.write("\r\n");
      out.write("        if (window.XMLHttpRequest) {\r\n");
      out.write("            // code for IE7+, Firefox, Chrome, Opera, Safari\r\n");
      out.write("            xmlHttp=new XMLHttpRequest();    //创建 XMLHttpRequest对象\r\n");
      out.write("        }\r\n");
      out.write("        else {\r\n");
      out.write("            // code for IE6, IE5\r\n");
      out.write("            xmlHttp=new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        xmlHttp.onreadystatechange=function() {\r\n");
      out.write("            //onreadystatechange — 当readystate变化时调用后面的方法\r\n");
      out.write("\r\n");
      out.write("            if (xmlHttp.readyState == 4) {\r\n");
      out.write("                //xmlHttp.readyState == 4    ——    finished downloading response\r\n");
      out.write("\r\n");
      out.write("                if (xmlHttp.status == 200) {\r\n");
      out.write("                    //xmlHttp.status == 200        ——    服务器反馈正常\r\n");
      out.write("\r\n");
      out.write("                    document.getElementById(\"content\").innerHTML=xmlHttp.responseText;    //重设页面中id=\"content\"的div里的内容\r\n");
      out.write("                    executeScript(xmlHttp.responseText);    //执行从服务器返回的页面内容里包含的JavaScript函数\r\n");
      out.write("                }\r\n");
      out.write("                //错误状态处理\r\n");
      out.write("                else if (xmlHttp.status == 404){\r\n");
      out.write("                    alert(\"出错了☹   （错误代码：404 Not Found），……！\");\r\n");
      out.write("                    /* 对404的处理 */\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("                else if (xmlHttp.status == 403) {\r\n");
      out.write("                    alert(\"出错了☹   （错误代码：403 Forbidden），……\");\r\n");
      out.write("                    /* 对403的处理  */\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("                else {\r\n");
      out.write("                    alert(\"出错了☹   （错误代码：\" + request.status + \"），……\");\r\n");
      out.write("                    /* 对出现了其他错误代码所示错误的处理   */\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        //把请求发送到服务器上的指定文件（url指向的文件）进行处理\r\n");
      out.write("        xmlHttp.open(\"GET\", url, true);        //true表示异步处理\r\n");
      out.write("        xmlHttp.send();\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
