/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.22
 * Generated at: 2019-09-04 12:52:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/apache-maven-3.6.1/repo/org/glassfish/web/jstl-impl/1.2/jstl-impl-1.2.jar!/META-INF/fmt-1_0.tld", Long.valueOf(1308098170000L));
    _jspx_dependants.put("file:/D:/apache-maven-3.6.1/repo/org/apache/taglibs/taglibs-standard-impl/1.2.1/taglibs-standard-impl-1.2.1.jar", Long.valueOf(1565943509132L));
    _jspx_dependants.put("jar:file:/D:/apache-maven-3.6.1/repo/org/apache/taglibs/taglibs-standard-impl/1.2.1/taglibs-standard-impl-1.2.1.jar!/META-INF/c-1_1.tld", Long.valueOf(1384339662000L));
    _jspx_dependants.put("file:/D:/apache-maven-3.6.1/repo/org/glassfish/web/jstl-impl/1.2/jstl-impl-1.2.jar", Long.valueOf(1565943376399L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 String path = request.getContextPath();
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("    <!-- meta data -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"referrer\" content=\"never\">\r\n");
      out.write("    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("\r\n");
      out.write("    <!--font-family-->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- title of site -->\r\n");
      out.write("    <title>首页</title>\r\n");
      out.write("    <!--font-awesome.min.css-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/assets/css/font-awesome.min.css\">\r\n");
      out.write("    <!--linear icon css-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/assets/css/linearicons.css\">\r\n");
      out.write("    <!--animate.css-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/assets/css/animate.css\">\r\n");
      out.write("    <!-- Icomoon Icon Fonts-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/assets/css/icomoon.css\">\r\n");
      out.write("    <!-- Magnific Popup -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/assets/css/bootstrap-datepicker.min.css\">\r\n");
      out.write("    <!--flaticon.css-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/assets/css/flaticon.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/assets/css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--slick.css-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/assets/css/slick.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/assets/css/slick-theme.css\">\r\n");
      out.write("    <!--bootstrap.min.css-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/assets/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- bootsnav -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/assets/css/bootsnav.css\" >\r\n");
      out.write("    <!--style.css-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/assets/css/style.css\">\r\n");
      out.write("    <!--responsive.css-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/assets/css/responsive.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/assets/css/changeimg.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/assets/css/reset.css\">\r\n");
      out.write("    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <style>\r\n");
      out.write("        *{padding: 0px;margin: 0px;}\r\n");
      out.write("        #flash{width:1200px;height: 535px;margin: 0px auto;position: relative;float: left}\r\n");
      out.write("        #flash #play{width:1200px;height: 535px;list-style: none;position:absolute;top:0px;left:0px;}\r\n");
      out.write("        #flash #play li{display: none;position:absolute;top:0px;left:0px;}\r\n");
      out.write("        #flash #play li img{float: left;}\r\n");
      out.write("        #button{position: absolute;bottom:20px;left:470px;list-style: none;}\r\n");
      out.write("        #button li{margin-left: 10px;float: left;}\r\n");
      out.write("        #button li div{width:12px;height: 12px;background:#DDDDDD;border-radius: 6px;cursor: pointer;}\r\n");
      out.write("        #prev{width:40px;height:63px;background:url(images/beijing.png) 0px 0px;position: absolute;top:205px;left:10px;z-index: 1;}\r\n");
      out.write("        #next{width:40px;height:63px;background:url(images/beijing.png) -40px 0px;position: absolute;top:205px;right:10px;z-index: 1;}\r\n");
      out.write("        #prev:hover{background:url(images/beijing.png) 0px -62px;}\r\n");
      out.write("        #next:hover{background:url(images/beijing.png) -40px -62px;}\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/js/script.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        function addsub() {\r\n");
      out.write("            var sname = document.getElementById(\"form-sname\");\r\n");
      out.write("            var beginplace = document.getElementById(\"form-beginplace\");\r\n");
      out.write("            var ssname = document.getElementById(\"sname\");\r\n");
      out.write("            var bbeginplace = document.getElementById(\"beginplace\");\r\n");
      out.write("            sname.value = ssname.value;\r\n");
      out.write("            beginplace.value = bbeginplace.value;\r\n");
      out.write("            var subform = document.getElementById(\"subform\");\r\n");
      out.write("            subform.submit();\r\n");
      out.write("        }\r\n");
      out.write("        function sub(id) {\r\n");
      out.write("            if (\"visitor\" == \"");
      out.print((String)session.getAttribute("type"));
      out.write("\"){\r\n");
      out.write("                alert(\"请登录后再使用该功能！\")\r\n");
      out.write("                window.location.href = \"/travel/index.jsp\";\r\n");
      out.write("            } else{\r\n");
      out.write("                var form = document.getElementById(id);\r\n");
      out.write("                form.submit();\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!--[if lte IE 9]>\r\n");
      out.write("<p class=\"browserupgrade\">You are using an <strong>outdated</strong> browser. Please <a href=\"https://browsehappy.com/\">upgrade your browser</a> to improve your experience and security.</p>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\r\n");
      out.write("<!--header-top start -->\r\n");
      out.write("<header id=\"header-top\" class=\"header-top\">\r\n");
      out.write("    <ul>\r\n");
      out.write("        <li>\r\n");
      out.write("            <div class=\"header-top-left\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li class=\"select-opt\">\r\n");
      out.write("                        <a href=\"#\"><span class=\"lnr lnr-magnifier\"></span></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"head-responsive-right pull-right\">\r\n");
      out.write("            <div class=\"header-top-right\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li class=\"header-top-contact\">\r\n");
      out.write("                        <a href=\"/travel/getPersonal\">个人信息</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"header-top-contact\">\r\n");
      out.write("                        <a href=\"/travel/index.jsp\">登录</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"header-top-contact\">\r\n");
      out.write("                        <a href=\"/travel/register.jsp\">注册</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("</header><!--/.header-top-->\r\n");
      out.write("<!--header-top end -->\r\n");
      out.write("\r\n");
      out.write("<!-- top-area Start -->\r\n");
      out.write("<section class=\"top-area\">\r\n");
      out.write("    <div class=\"header-area\">\r\n");
      out.write("        <!-- Start Navigation -->\r\n");
      out.write("        <nav class=\"navbar navbar-default bootsnav  navbar-sticky navbar-scrollspy\"  data-minus-value-desktop=\"70\" data-minus-value-mobile=\"55\" data-speed=\"1000\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("                <!-- Start Header Navigation -->\r\n");
      out.write("                <div class=\"navbar-header\">\r\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#navbar-menu\">\r\n");
      out.write("                        <i class=\"fa fa-bars\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <a class=\"navbar-brand\" href=\"#\">旅游<span>资源</span></a>\r\n");
      out.write("\r\n");
      out.write("                </div><!--/.navbar-header-->\r\n");
      out.write("                <!-- End Header Navigation -->\r\n");
      out.write("\r\n");
      out.write("                <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("                <div class=\"collapse navbar-collapse menu-ui-design\" id=\"navbar-menu\">\r\n");
      out.write("                    <ul class=\"nav navbar-nav navbar-right\" data-in=\"fadeInDown\" data-out=\"fadeOutUp\">\r\n");
      out.write("                        <li class=\" scroll active\"><a href=\"#home\">首页</a></li>\r\n");
      out.write("                        <li class=\"scroll\"><a href=\"#works\">景点推荐</a></li>\r\n");
      out.write("                        <li class=\"scroll\"><a href=\"#home\">景点查询</a></li>\r\n");
      out.write("                        <li><a href=\"/travel/myorders.jsp\">历史订单</a></li>\r\n");
      out.write("                    </ul><!--/.nav -->\r\n");
      out.write("                </div><!-- /.navbar-collapse -->\r\n");
      out.write("            </div><!--/.container-->\r\n");
      out.write("        </nav><!--/nav-->\r\n");
      out.write("        <!-- End Navigation -->\r\n");
      out.write("    </div><!--/.header-area-->\r\n");
      out.write("    <div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("</section><!-- /.top-area-->\r\n");
      out.write("<!-- top-area End -->\r\n");
      out.write("<div class=\"head-photo-text\">\r\n");
      out.write("    <div class=\"photo-content\">\r\n");
      out.write("        <div id=\"flash\">\r\n");
      out.write("            <div id=\"prev\"></div>\r\n");
      out.write("            <div id=\"next\"></div>\r\n");
      out.write("            <ul id=\"play\">\r\n");
      out.write("                <li style=\"display: block;\"><img src=\"");
      out.print(path);
      out.write("/images/1.jpg\" alt=\"\" /></li>\r\n");
      out.write("                <li><img src=\"");
      out.print(path);
      out.write("/images/2.jpg\" alt=\"\" /></li>\r\n");
      out.write("                <li><img src=\"");
      out.print(path);
      out.write("/images/3.jpg\" alt=\"\" /></li>\r\n");
      out.write("                <li><img src=\"");
      out.print(path);
      out.write("/images/4.jpg\" alt=\"\" /></li>\r\n");
      out.write("                <li><img src=\"");
      out.print(path);
      out.write("/images/5.jpg\" alt=\"\" /></li>\r\n");
      out.write("                <li><img src=\"");
      out.print(path);
      out.write("/images/6.jpg\" alt=\"\" /></li>\r\n");
      out.write("                <li><img src=\"");
      out.print(path);
      out.write("/images/7.jpg\" alt=\"\" /></li>\r\n");
      out.write("                <li><img src=\"");
      out.print(path);
      out.write("/images/8.jpg\" alt=\"\" /></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul id=\"button\">\r\n");
      out.write("                <li><div style=\"background: #A10000;\"></div></li>\r\n");
      out.write("                <li><div></div></li>\r\n");
      out.write("                <li><div></div></li>\r\n");
      out.write("                <li><div></div></li>\r\n");
      out.write("                <li><div></div></li>\r\n");
      out.write("                <li><div></div></li>\r\n");
      out.write("                <li><div></div></li>\r\n");
      out.write("                <li><div></div></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"show-box\">\r\n");
      out.write("        <div class=\"info-box\">\r\n");
      out.write("            <ul class=\"tab-nav\">\r\n");
      out.write("                <li id=\"li-1\" class=\"li-nav li-nav-hover li-border\">公告</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div id=\"box-1\" style=\"display: block\" class=\"hiddenBox\">\r\n");
      out.write("\r\n");
      out.write("                <a href=\"#\">公告1****************************************</a>\r\n");
      out.write("                <a href=\"#\">公告2****************************************</a>\r\n");
      out.write("                <a href=\"#\">公告3****************************************</a>\r\n");
      out.write("                <a href=\"#\">公告4****************************************</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--welcome-hero start -->\r\n");
      out.write("<section id=\"home\" class=\"welcome-hero\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"welcome-hero-txt\">\r\n");
      out.write("            <h2>探索自然 <br>发现美好 </h2>\r\n");
      out.write("            <p>\r\n");
      out.write("                尽在旅游资源管理网\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"welcome-hero-serch-box\">\r\n");
      out.write("            <form action=\"/travel/getBusiness\" name=\"subform\" id=\"subform\" method=\"post\" hidden=\"hidden\">\r\n");
      out.write("                <input type=\"text\" id=\"form-sname\" name=\"form-sname\" value=\"\">\r\n");
      out.write("                <input type=\"text\" id=\"form-beginplace\" name=\"form-beginplace\" value=\"\">\r\n");
      out.write("            </form>\r\n");
      out.write("            <div class=\"welcome-hero-form\">\r\n");
      out.write("                <div class=\"single-welcome-hero-form\">\r\n");
      out.write("                    <h3>出发地</h3>\r\n");
      out.write("                    <form>\r\n");
      out.write("                        <input id=\"beginplace\" name=\"beginplace\" type=\"text\" placeholder=\"例: 南京\" value=\"\"/>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <div class=\"welcome-hero-form-icon\">\r\n");
      out.write("                        <i class=\"flaticon-list-with-dots\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"single-welcome-hero-form\">\r\n");
      out.write("                    <h3>目标景点</h3>\r\n");
      out.write("                    <form>\r\n");
      out.write("                        <input id=\"sname\" name=\"sname\" type=\"text\" placeholder=\"例: 乐山大佛\" value=\"\"/>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <div class=\"welcome-hero-form-icon\">\r\n");
      out.write("                        <i class=\"flaticon-list-with-dots\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"welcome-hero-serch\">\r\n");
      out.write("                <button class=\"welcome-hero-btn\" onclick=\"addsub()\">\r\n");
      out.write("                    search  <i data-feather=\"search\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</section><!--/.welcome-hero-->\r\n");
      out.write("<!--welcome-hero end -->\r\n");
      out.write("\r\n");
      out.write("<!--list-topics start -->\r\n");
      out.write("<section id=\"list-topics\" class=\"list-topics\">\r\n");
      out.write("    <div class=\"smallcontainer\">\r\n");
      out.write("        <div class=\"list-topics-content\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <div class=\"single-list-topics-content\">\r\n");
      out.write("                        <div class=\"single-list-topics-icon\">\r\n");
      out.write("                            <i class=\"flaticon-restaurant\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h2><a href=\"#\">餐饮</a></h2>\r\n");
      out.write("                        <p>150 listings</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <div class=\"single-list-topics-content\">\r\n");
      out.write("                        <div class=\"single-list-topics-icon\">\r\n");
      out.write("                            <i class=\"flaticon-travel\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h2><a href=\"#\">目的地</a></h2>\r\n");
      out.write("                        <p>214 listings</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <div class=\"single-list-topics-content\">\r\n");
      out.write("                        <div class=\"single-list-topics-icon\">\r\n");
      out.write("                            <i class=\"flaticon-building\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h2><a href=\"#\">旅店住宿</a></h2>\r\n");
      out.write("                        <p>185 listings</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <div class=\"single-list-topics-content\">\r\n");
      out.write("                        <div class=\"single-list-topics-icon\">\r\n");
      out.write("                            <i class=\"flaticon-pills\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h2><a href=\"#\">医疗保障</a></h2>\r\n");
      out.write("                        <p>200 listings</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <div class=\"single-list-topics-content\">\r\n");
      out.write("                        <div class=\"single-list-topics-icon\">\r\n");
      out.write("                            <i class=\"flaticon-transport\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h2><a href=\"#\">出行方式</a></h2>\r\n");
      out.write("                        <p>120 listings</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div><!--/.container-->\r\n");
      out.write("\r\n");
      out.write("</section><!--/.list-topics-->\r\n");
      out.write("<!--list-topics end-->\r\n");
      out.write("\r\n");
      out.write("<!--works start -->\r\n");
      out.write("<section id=\"works\" class=\"works\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"section-header\">\r\n");
      out.write("            <h2>景点推荐</h2>\r\n");
      out.write("            <p>来次美好的旅行怎么样？</p>\r\n");
      out.write("        </div><!--/.section-header-->\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div><!--/.container-->\r\n");
      out.write("\r\n");
      out.write("</section><!--/.works-->\r\n");
      out.write("<!--works end -->\r\n");
      out.write("\r\n");
      out.write("<!--footer start-->\r\n");
      out.write("<footer id=\"footer\"  class=\"footer\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"footer-menu\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-sm-3\">\r\n");
      out.write("                    <div class=\"navbar-header\">\r\n");
      out.write("                        <a class=\"navbar-brand\" href=\"#\">旅游<span>资源</span></a>\r\n");
      out.write("                    </div><!--/.navbar-header-->\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-9\">\r\n");
      out.write("                    <ul class=\"footer-menu-item\">\r\n");
      out.write("                        <li class=\"scroll\"><a href=\"#works\">how it works</a></li>\r\n");
      out.write("                        <li class=\"scroll\"><a href=\"#home\">explore</a></li>\r\n");
      out.write("                    </ul><!--/.nav -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div><!--/.container-->\r\n");
      out.write("\r\n");
      out.write("    <div id=\"scroll-Top\">\r\n");
      out.write("        <div class=\"return-to-top\">\r\n");
      out.write("            <i class=\"fa fa-angle-up \" id=\"scroll-top1\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"Back to Top\" aria-hidden=\"true\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div><!--/.scroll-Top-->\r\n");
      out.write("\r\n");
      out.write("</footer><!--/.footer-->\r\n");
      out.write("<!--footer end-->\r\n");
      out.write("\r\n");
      out.write("<!-- Include all js compiled plugins (below), or include individual files as needed -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/assets/js/jquery.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--bootstrap.min.js-->\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- bootsnav js -->\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/assets/js/bootsnav.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--feather.min.js-->\r\n");
      out.write("<script  src=\"");
      out.print(path);
      out.write("/assets/js/feather.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- counter js -->\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/assets/js/jquery.counterup.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/assets/js/waypoints.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--slick.min.js-->\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/assets/js/slick.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--Custom JS-->\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/assets/js/custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /main.jsp(328,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty businesslist}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                ");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /main.jsp(329,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("d");
      // /main.jsp(329,16) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${businesslist}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                    <form action=\"/travel/findonebusiness\" name=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" hidden=\"hidden\" method=\"post\" id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                        <input type=\"text\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" hidden=\"hidden\" name=\"businessid\" id=\"businessid\">\r\n");
            out.write("                    </form>\r\n");
            out.write("                    <div class=\"col-lg-4 col-md-4 col-sm-6\">\r\n");
            out.write("                        <a href=\"javascript:void(0);\" onclick=\"sub(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(")\" class=\"fh5co-card-item image-popup\">\r\n");
            out.write("                            <figure>\r\n");
            out.write("                                <div class=\"overlay\"><i class=\"ti-plus\"></i></div>\r\n");
            out.write("                                <img src=\"/travel/scenic/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.p1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"Image\" class=\"img-responsive\">\r\n");
            out.write("                            </figure>\r\n");
            out.write("                            <div class=\"fh5co-text\">\r\n");
            out.write("                                <h2>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.scenicname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h2>\r\n");
            out.write("                                <p>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${d.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("                            </div>\r\n");
            out.write("                        </a>\r\n");
            out.write("                    </div>\r\n");
            out.write("                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
