/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.22
 * Generated at: 2019-09-02 17:00:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.njust.travel.entity.Vip;
import com.njust.travel.entity.Agency;

public final class personal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.njust.travel.entity.Vip");
    _jspx_imports_classes.add("com.njust.travel.entity.Agency");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>用户信息</title>\r\n");
      out.write("    <link href=\"assets/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("    <link href=\"assets/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"assets/css/styleforuserinfo.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("    <!-- bootstrap2环境使用 -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/b.page.css\" type=\"text/css\">\r\n");
      out.write("    <!-- bootstrap3环境使用 -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/b.page.bootstrap3.css\" type=\"text/css\">\r\n");
      out.write("    <script>\r\n");
      out.write("        function x1() {\r\n");
      out.write("            var form1 = document.getElementById(\"form1\");\r\n");
      out.write("            form1.action = \"/travel/updatevipinfo\";\r\n");
      out.write("            form1.submit();\r\n");
      out.write("        }\r\n");
      out.write("        function x2() {\r\n");
      out.write("            var form2 = document.getElementById(\"form2\");\r\n");
      out.write("            form2.action = \"/travel/updateagencyinfo\";\r\n");
      out.write("            form2.submit();\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bgimg\">\r\n");
      out.write("<!-- about -->\r\n");
      out.write("<!--header-top start -->\r\n");
      out.write("<nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"#\"><span>用户</span>信息页</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"toptoright\"> <a href=\"index.jsp\"class=\"setwordcolor\">退出登录</a></div>\r\n");
      out.write("    </div><!-- /.container-fluid -->\r\n");
      out.write("</nav>\r\n");
      out.write("<!--header-top end -->\r\n");

    String user = (String) session.getAttribute("user");
    String type = (String) session.getAttribute("type");
    if (type.equals("visitor")) {

      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        alert(\"请登录后尝试！\");\r\n");
      out.write("        window.location.href=\"/travel/index.jsp\";\r\n");
      out.write("    </script>\r\n");

    }
    else if (type.equals("admin")){

      out.write("\r\n");
      out.write("<div class=\"totop\" id=\"about\">\r\n");
      out.write("    <div class=\"form-bottom col-md-6 col-md-offset-3 form-box colorchange css1\">\r\n");
      out.write("        <form role=\"form\" action=\"#\" method=\"post\" class=\"\" id=\"form0\">\r\n");
      out.write("            <h1><a class=\"h1-left\"></a>个人信息修改</h1>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                用户名:<input type=\"text\" name=\"form-username\" placeholder=\"用户名\" class=\"form-username form-control\" id=\"form-username\" readonly=\"readonly\" value=\"");
      out.print(user);
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                账户类型:<input type=\"text\" name=\"form-type\" placeholder=\"账户类型\" class=\"form-password form-control\" id=\"form-type\" readonly=\"readonly\" value=\"管理员\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <button type=\"button\" class=\"btn\" onclick=\"window.location.href='adminmain.jsp'\">返回主页</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
}else if (type.equals("vip")){
    Vip vip = (Vip) session.getAttribute("vip");

      out.write("\r\n");
      out.write("<div class=\"totop\" id=\"about\">\r\n");
      out.write("    <div class=\"form-bottom col-md-6 col-md-offset-3 form-box colorchange css1\">\r\n");
      out.write("        <form role=\"form\" action=\"#\" method=\"post\" class=\"\" id=\"form1\">\r\n");
      out.write("            <h1><a class=\"h1-left\"></a>个人信息修改</h1>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <input type=\"text\" name=\"form-username\" placeholder=\"用户名\" class=\"form-username form-control\" id=\"form-nickname\" readonly=\"readonly\" value=\"");
      out.print(vip.getUsername());
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <input type=\"text\" name=\"form-age\" placeholder=\"年龄\" class=\"form-password form-control\" id=\"form-age\" value=\"");
      out.print(vip.getAge());
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <input type=\"text\" name=\"form-sex\" placeholder=\"性别\" class=\"form-password form-control\" id=\"form-sex\" value=\"");
      out.print(vip.getSex());
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <input type=\"text\" name=\"form-cid\" placeholder=\"身份证号码\" class=\"form-password form-control\" id=\"form-cid\" value=\"");
      out.print(vip.getCid());
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <input type=\"text\" name=\"form-tel\" placeholder=\"联系电话\" class=\"form-password form-control\" id=\"form-tel\" value=\"");
      out.print(vip.getTel());
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <input type=\"text\" name=\"form-mail\" placeholder=\"邮箱地址\" class=\"form-password form-control\" id=\"form-mail\" value=\"");
      out.print(vip.getEmail());
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"button\" class=\"btn\" onclick=\"x1()\">确认修改</button>\r\n");
      out.write("            <button type=\"button\" class=\"btn\" onclick=\"window.location.href='main.jsp'\">返回主页</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
}else if (type.equals("agency")){
    Agency agency = (Agency)session.getAttribute("agency");

      out.write("\r\n");
      out.write("<div class=\"totop\" id=\"about\">\r\n");
      out.write("    <div class=\"form-bottom col-md-6 col-md-offset-3 form-box colorchange css1\">\r\n");
      out.write("        <form role=\"form\" action=\"#\" method=\"post\" class=\"\" id=\"form2\">\r\n");
      out.write("            <h1><a class=\"h1-left\"></a>个人信息修改</h1>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <input type=\"text\" name=\"form-username\" placeholder=\"用户名\" class=\"form-username form-control\" id=\"form-username1\" readonly=\"readonly\" value=\"");
      out.print(agency.getUsername());
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <input type=\"text\" name=\"form-aname\" placeholder=\"旅行社名\" class=\"form-password form-control\" id=\"form-aname\" value=\"");
      out.print(agency.getAgencyname());
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <input type=\"text\" name=\"form-pname\" placeholder=\"法人姓名\" class=\"form-password form-control\" id=\"form-pname\" value=\"");
      out.print(agency.getName());
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <input type=\"text\" name=\"form-cid\" placeholder=\"法人身份证号码\" class=\"form-password form-control\" id=\"form-cid1\" value=\"");
      out.print(agency.getCid());
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <input type=\"text\" name=\"form-tel\" placeholder=\"联系电话\" class=\"form-password form-control\" id=\"form-tel1\" value=\"");
      out.print(agency.getTel());
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <input type=\"text\" name=\"form-mail\" placeholder=\"邮箱地址\" class=\"form-password form-control\" id=\"form-mail1\" value=\"");
      out.print(agency.getEmail());
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <a href=\"");
      out.print("/travel/licence/"+agency.getLicencesite());
      out.write("\" class=\"form-password form-control\" readonly=\"readonly\">营业执照</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"button\" class=\"btn\" onclick=\"x2()\">确认修改</button>\r\n");
      out.write("            <button type=\"button\" class=\"btn\" onclick=\"window.location.href='agencymain.jsp'\">返回主页</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
}
      out.write("\r\n");
      out.write("<!-- //about-bottom -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
